### PR TITLE
Implement getGameScoreAndStats call for NBA.

### PR DESCRIPTION
**Pull request by queso**
Would you mind releasing a new version to NPM if you accept this request?

Hate to push my own version if you plan to still maintain your version.  Also, thanks for building this in the first place, saved me some time.

### CODE REVIEW

**Comment by queso** [comment]
Is this project being maintained anymore?  I hate to fork and push a seperate package up to Npmjs.org, but this is becoming an issue for me.

**Comment by rgerard** [comment]
Hi @queso, sorry about the delay. I've been out of the country for the last 10 days or so. This LGTM, so I'll merge now, and publish a new version of the NPM tonight.

**Comment by queso** [comment]
Sweet.  We are trying to beta test this for a client, so I would love to get the Npm updated ASAP if you have time, thx for being on this today!

**Comment by queso** [comment]
If you could deploy that tonight, it would be super helpful.  I use Meteor.js and it doesn't work with github based npm packages.

If you can't update, I will have to release a version myself.

**Comment by rgerard** [comment]
@queso just published!

**Pull request merged**
